repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: ["--line-length", "120"]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.3
    hooks:
      - id: isort
        args: ["--project", "experitorch"]